# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotgui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PythIon(object):
    def setupUi(self, PythIon):
        PythIon.setObjectName("PythIon")
        PythIon.resize(1118, 849)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PythIon.sizePolicy().hasHeightForWidth())
        PythIon.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/PythIon/pythionlogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PythIon.setWindowIcon(icon)
        PythIon.setAutoFillBackground(False)
        PythIon.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(PythIon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.eventinfolabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventinfolabel.sizePolicy().hasHeightForWidth())
        self.eventinfolabel.setSizePolicy(sizePolicy)
        self.eventinfolabel.setMinimumSize(QtCore.QSize(500, 15))
        self.eventinfolabel.setMaximumSize(QtCore.QSize(500, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.eventinfolabel.setFont(font)
        self.eventinfolabel.setText("")
        self.eventinfolabel.setObjectName("eventinfolabel")
        self.gridLayout_10.addWidget(self.eventinfolabel, 3, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.baselinebutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baselinebutton.sizePolicy().hasHeightForWidth())
        self.baselinebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.baselinebutton.setFont(font)
        self.baselinebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.baselinebutton.setAutoFillBackground(False)
        self.baselinebutton.setObjectName("baselinebutton")
        self.gridLayout_14.addWidget(self.baselinebutton, 3, 0, 1, 1)
        self.loadbutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadbutton.sizePolicy().hasHeightForWidth())
        self.loadbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.loadbutton.setFont(font)
        self.loadbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loadbutton.setAutoFillBackground(False)
        self.loadbutton.setObjectName("loadbutton")
        self.gridLayout_14.addWidget(self.loadbutton, 2, 0, 1, 1)
        self.analyzebutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyzebutton.sizePolicy().hasHeightForWidth())
        self.analyzebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.analyzebutton.setFont(font)
        self.analyzebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.analyzebutton.setAutoFillBackground(False)
        self.analyzebutton.setObjectName("analyzebutton")
        self.gridLayout_14.addWidget(self.analyzebutton, 4, 0, 1, 1)
        self.previousfilebutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousfilebutton.sizePolicy().hasHeightForWidth())
        self.previousfilebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.previousfilebutton.setFont(font)
        self.previousfilebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.previousfilebutton.setAutoFillBackground(False)
        self.previousfilebutton.setObjectName("previousfilebutton")
        self.gridLayout_14.addWidget(self.previousfilebutton, 3, 1, 1, 1)
        self.nextfilebutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextfilebutton.sizePolicy().hasHeightForWidth())
        self.nextfilebutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.nextfilebutton.setFont(font)
        self.nextfilebutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nextfilebutton.setAutoFillBackground(False)
        self.nextfilebutton.setObjectName("nextfilebutton")
        self.gridLayout_14.addWidget(self.nextfilebutton, 2, 1, 1, 1)
        self.clearscatterbutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearscatterbutton.sizePolicy().hasHeightForWidth())
        self.clearscatterbutton.setSizePolicy(sizePolicy)
        self.clearscatterbutton.setMinimumSize(QtCore.QSize(0, 5))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.clearscatterbutton.setFont(font)
        self.clearscatterbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clearscatterbutton.setAutoFillBackground(False)
        self.clearscatterbutton.setObjectName("clearscatterbutton")
        self.gridLayout_14.addWidget(self.clearscatterbutton, 1, 1, 1, 1)
        self.invertbutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invertbutton.sizePolicy().hasHeightForWidth())
        self.invertbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.invertbutton.setFont(font)
        self.invertbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.invertbutton.setAutoFillBackground(False)
        self.invertbutton.setObjectName("invertbutton")
        self.gridLayout_14.addWidget(self.invertbutton, 4, 1, 1, 1)
        self.cutbutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutbutton.sizePolicy().hasHeightForWidth())
        self.cutbutton.setSizePolicy(sizePolicy)
        self.cutbutton.setMinimumSize(QtCore.QSize(0, 5))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cutbutton.setFont(font)
        self.cutbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cutbutton.setAutoFillBackground(False)
        self.cutbutton.setObjectName("cutbutton")
        self.gridLayout_14.addWidget(self.cutbutton, 1, 0, 1, 1)
        self.loaddatabutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loaddatabutton.sizePolicy().hasHeightForWidth())
        self.loaddatabutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.loaddatabutton.setFont(font)
        self.loaddatabutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loaddatabutton.setAutoFillBackground(False)
        self.loaddatabutton.setObjectName("loaddatabutton")
        self.gridLayout_14.addWidget(self.loaddatabutton, 0, 0, 1, 1)
        self.fitbutton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitbutton.sizePolicy().hasHeightForWidth())
        self.fitbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fitbutton.setFont(font)
        self.fitbutton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fitbutton.setAutoFillBackground(False)
        self.fitbutton.setObjectName("fitbutton")
        self.gridLayout_14.addWidget(self.fitbutton, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.thresholdentry = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdentry.sizePolicy().hasHeightForWidth())
        self.thresholdentry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.thresholdentry.setFont(font)
        self.thresholdentry.setObjectName("thresholdentry")
        self.gridLayout_15.addWidget(self.thresholdentry, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_15.addWidget(self.label_5, 2, 0, 1, 1)
        self.eventbufferentry = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventbufferentry.sizePolicy().hasHeightForWidth())
        self.eventbufferentry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.eventbufferentry.setFont(font)
        self.eventbufferentry.setObjectName("eventbufferentry")
        self.gridLayout_15.addWidget(self.eventbufferentry, 2, 1, 1, 1)
        self.outputsamplerateentry = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsamplerateentry.sizePolicy().hasHeightForWidth())
        self.outputsamplerateentry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.outputsamplerateentry.setFont(font)
        self.outputsamplerateentry.setObjectName("outputsamplerateentry")
        self.gridLayout_15.addWidget(self.outputsamplerateentry, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_15.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_15.addWidget(self.label_2, 1, 0, 1, 1)
        self.LPentry = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LPentry.sizePolicy().hasHeightForWidth())
        self.LPentry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.LPentry.setFont(font)
        self.LPentry.setObjectName("LPentry")
        self.gridLayout_15.addWidget(self.LPentry, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 4, 0, 1, 1)
        self.levelthresholdentry = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.levelthresholdentry.sizePolicy().hasHeightForWidth())
        self.levelthresholdentry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.levelthresholdentry.setFont(font)
        self.levelthresholdentry.setObjectName("levelthresholdentry")
        self.gridLayout_15.addWidget(self.levelthresholdentry, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_15, 0, 3, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.signalplot = GraphicsLayoutWidget(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalplot.sizePolicy().hasHeightForWidth())
        self.signalplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.signalplot.setFont(font)
        self.signalplot.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.signalplot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signalplot.setObjectName("signalplot")
        self.gridLayout_4.addWidget(self.signalplot, 0, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.groupBox1)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.voltageplotwin = GraphicsLayoutWidget(self.tab)
        self.voltageplotwin.setGeometry(QtCore.QRect(0, 0, 1061, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voltageplotwin.sizePolicy().hasHeightForWidth())
        self.voltageplotwin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.voltageplotwin.setFont(font)
        self.voltageplotwin.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.voltageplotwin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.voltageplotwin.setObjectName("voltageplotwin")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(-40, -2, 1101, 252))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.eventplot = GraphicsLayoutWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventplot.sizePolicy().hasHeightForWidth())
        self.eventplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.eventplot.setFont(font)
        self.eventplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";\n"
"border-color: rgb(0, 0, 0);")
        self.eventplot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.eventplot.setObjectName("eventplot")
        self.horizontalLayout_3.addWidget(self.eventplot)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777206))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.East)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.scattertab = QtWidgets.QWidget()
        self.scattertab.setObjectName("scattertab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scattertab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scatterplot = GraphicsLayoutWidget(self.scattertab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scatterplot.sizePolicy().hasHeightForWidth())
        self.scatterplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.scatterplot.setFont(font)
        self.scatterplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.scatterplot.setObjectName("scatterplot")
        self.gridLayout_3.addWidget(self.scatterplot, 0, 0, 1, 1)
        self.tabWidget.addTab(self.scattertab, "")
        self.frachisttab = QtWidgets.QWidget()
        self.frachisttab.setObjectName("frachisttab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frachisttab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frachistplot = GraphicsLayoutWidget(self.frachisttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frachistplot.sizePolicy().hasHeightForWidth())
        self.frachistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.frachistplot.setFont(font)
        self.frachistplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.frachistplot.setObjectName("frachistplot")
        self.gridLayout_6.addWidget(self.frachistplot, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frachisttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.fracbins = QtWidgets.QLineEdit(self.frachisttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fracbins.sizePolicy().hasHeightForWidth())
        self.fracbins.setSizePolicy(sizePolicy)
        self.fracbins.setAlignment(QtCore.Qt.AlignCenter)
        self.fracbins.setObjectName("fracbins")
        self.horizontalLayout_2.addWidget(self.fracbins)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.frachisttab, "")
        self.delitab = QtWidgets.QWidget()
        self.delitab.setObjectName("delitab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.delitab)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.delihistplot = GraphicsLayoutWidget(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delihistplot.sizePolicy().hasHeightForWidth())
        self.delihistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.delihistplot.setFont(font)
        self.delihistplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.delihistplot.setObjectName("delihistplot")
        self.gridLayout_7.addWidget(self.delihistplot, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.delitab)
        self.label_9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.delibins = QtWidgets.QLineEdit(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delibins.sizePolicy().hasHeightForWidth())
        self.delibins.setSizePolicy(sizePolicy)
        self.delibins.setAlignment(QtCore.Qt.AlignCenter)
        self.delibins.setObjectName("delibins")
        self.horizontalLayout_7.addWidget(self.delibins)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.delirange0 = QtWidgets.QLineEdit(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delirange0.sizePolicy().hasHeightForWidth())
        self.delirange0.setSizePolicy(sizePolicy)
        self.delirange0.setAlignment(QtCore.Qt.AlignCenter)
        self.delirange0.setObjectName("delirange0")
        self.horizontalLayout_9.addWidget(self.delirange0)
        self.label_12 = QtWidgets.QLabel(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.delirange1 = QtWidgets.QLineEdit(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delirange1.sizePolicy().hasHeightForWidth())
        self.delirange1.setSizePolicy(sizePolicy)
        self.delirange1.setAlignment(QtCore.Qt.AlignCenter)
        self.delirange1.setObjectName("delirange1")
        self.horizontalLayout_9.addWidget(self.delirange1)
        self.label_11 = QtWidgets.QLabel(self.delitab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.tabWidget.addTab(self.delitab, "")
        self.dwelltab = QtWidgets.QWidget()
        self.dwelltab.setObjectName("dwelltab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dwelltab)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.dwellhistplot = GraphicsLayoutWidget(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellhistplot.sizePolicy().hasHeightForWidth())
        self.dwellhistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.dwellhistplot.setFont(font)
        self.dwellhistplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.dwellhistplot.setObjectName("dwellhistplot")
        self.gridLayout_8.addWidget(self.dwellhistplot, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.dwellbins = QtWidgets.QLineEdit(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellbins.sizePolicy().hasHeightForWidth())
        self.dwellbins.setSizePolicy(sizePolicy)
        self.dwellbins.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellbins.setObjectName("dwellbins")
        self.horizontalLayout_14.addWidget(self.dwellbins)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.dwellrange0 = QtWidgets.QLineEdit(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellrange0.sizePolicy().hasHeightForWidth())
        self.dwellrange0.setSizePolicy(sizePolicy)
        self.dwellrange0.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellrange0.setObjectName("dwellrange0")
        self.horizontalLayout_10.addWidget(self.dwellrange0)
        self.label_23 = QtWidgets.QLabel(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_10.addWidget(self.label_23)
        self.dwellrange1 = QtWidgets.QLineEdit(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellrange1.sizePolicy().hasHeightForWidth())
        self.dwellrange1.setSizePolicy(sizePolicy)
        self.dwellrange1.setAlignment(QtCore.Qt.AlignCenter)
        self.dwellrange1.setObjectName("dwellrange1")
        self.horizontalLayout_10.addWidget(self.dwellrange1)
        self.label_24 = QtWidgets.QLabel(self.dwelltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        self.gridLayout_8.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.tabWidget.addTab(self.dwelltab, "")
        self.dttab = QtWidgets.QWidget()
        self.dttab.setObjectName("dttab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.dttab)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.dthistplot = GraphicsLayoutWidget(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dthistplot.sizePolicy().hasHeightForWidth())
        self.dthistplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kozuka Gothic Pro L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.dthistplot.setFont(font)
        self.dthistplot.setStyleSheet("font: 25 20pt \"Kozuka Gothic Pro L\";")
        self.dthistplot.setObjectName("dthistplot")
        self.gridLayout_9.addWidget(self.dthistplot, 0, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_25 = QtWidgets.QLabel(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_18.addWidget(self.label_25)
        self.dtbins = QtWidgets.QLineEdit(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtbins.sizePolicy().hasHeightForWidth())
        self.dtbins.setSizePolicy(sizePolicy)
        self.dtbins.setAlignment(QtCore.Qt.AlignCenter)
        self.dtbins.setObjectName("dtbins")
        self.horizontalLayout_18.addWidget(self.dtbins)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtWidgets.QLabel(self.dttab)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.dtrange0 = QtWidgets.QLineEdit(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtrange0.sizePolicy().hasHeightForWidth())
        self.dtrange0.setSizePolicy(sizePolicy)
        self.dtrange0.setAlignment(QtCore.Qt.AlignCenter)
        self.dtrange0.setObjectName("dtrange0")
        self.horizontalLayout_19.addWidget(self.dtrange0)
        self.label_27 = QtWidgets.QLabel(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_19.addWidget(self.label_27)
        self.dtrange1 = QtWidgets.QLineEdit(self.dttab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtrange1.sizePolicy().hasHeightForWidth())
        self.dtrange1.setSizePolicy(sizePolicy)
        self.dtrange1.setAlignment(QtCore.Qt.AlignCenter)
        self.dtrange1.setObjectName("dtrange1")
        self.horizontalLayout_19.addWidget(self.dtrange1)
        self.label_28 = QtWidgets.QLabel(self.dttab)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_19.addWidget(self.label_28)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.gridLayout_9.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.tabWidget.addTab(self.dttab, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.ivplot = PlotWidget(self.tab_3)
        self.ivplot.setGeometry(QtCore.QRect(610, 0, 451, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ivplot.sizePolicy().hasHeightForWidth())
        self.ivplot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ivplot.setFont(font)
        self.ivplot.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.ivplot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ivplot.setObjectName("ivplot")
        self.cutData = PlotWidget(self.tab_3)
        self.cutData.setGeometry(QtCore.QRect(0, 0, 601, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutData.sizePolicy().hasHeightForWidth())
        self.cutData.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cutData.setFont(font)
        self.cutData.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.cutData.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cutData.setObjectName("cutData")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.poresizeOutput = QtWidgets.QLabel(self.tab_4)
        self.poresizeOutput.setGeometry(QtCore.QRect(690, 70, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.poresizeOutput.setFont(font)
        self.poresizeOutput.setObjectName("poresizeOutput")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 341, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 30, 321, 42))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resistanceText = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.resistanceText.setObjectName("resistanceText")
        self.verticalLayout_2.addWidget(self.resistanceText)
        self.conductanceText = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.conductanceText.setObjectName("conductanceText")
        self.verticalLayout_2.addWidget(self.conductanceText)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 110, 341, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 321, 60))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.concentrationValue = SpinBox(self.gridLayoutWidget_3)
        self.concentrationValue.setSuffix("")
        self.concentrationValue.setMaximum(10.0)
        self.concentrationValue.setSingleStep(0.1)
        self.concentrationValue.setObjectName("concentrationValue")
        self.gridLayout_12.addWidget(self.concentrationValue, 0, 1, 1, 1)
        self.resistanceText_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.resistanceText_2.setObjectName("resistanceText_2")
        self.gridLayout_12.addWidget(self.resistanceText_2, 0, 0, 1, 1)
        self.resistanceText_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.resistanceText_3.setObjectName("resistanceText_3")
        self.gridLayout_12.addWidget(self.resistanceText_3, 1, 0, 1, 1)
        self.porelengthValue = SpinBox(self.gridLayoutWidget_3)
        self.porelengthValue.setObjectName("porelengthValue")
        self.gridLayout_12.addWidget(self.porelengthValue, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_5.setGeometry(QtCore.QRect(370, 20, 311, 181))
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setChecked(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 298, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.customCurrent = SpinBox(self.gridLayoutWidget_2)
        self.customCurrent.setObjectName("customCurrent")
        self.gridLayout_11.addWidget(self.customCurrent, 0, 1, 1, 1)
        self.CustomConductanceLabel_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CustomConductanceLabel_2.setObjectName("CustomConductanceLabel_2")
        self.gridLayout_11.addWidget(self.CustomConductanceLabel_2, 1, 0, 1, 1)
        self.customVoltage = SpinBox(self.gridLayoutWidget_2)
        self.customVoltage.setObjectName("customVoltage")
        self.gridLayout_11.addWidget(self.customVoltage, 1, 1, 1, 1)
        self.CustomConductanceLabel_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CustomConductanceLabel_3.setObjectName("CustomConductanceLabel_3")
        self.gridLayout_11.addWidget(self.CustomConductanceLabel_3, 0, 0, 1, 1)
        self.CustomConductanceLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CustomConductanceLabel.setObjectName("CustomConductanceLabel")
        self.gridLayout_11.addWidget(self.CustomConductanceLabel, 2, 0, 1, 1)
        self.customConductanceSpinBox = SpinBox(self.gridLayoutWidget_2)
        self.customConductanceSpinBox.setObjectName("customConductanceSpinBox")
        self.gridLayout_11.addWidget(self.customConductanceSpinBox, 2, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.powerSpecPlot = PlotWidget(self.tab_5)
        self.powerSpecPlot.setGeometry(QtCore.QRect(290, 10, 761, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerSpecPlot.sizePolicy().hasHeightForWidth())
        self.powerSpecPlot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.powerSpecPlot.setFont(font)
        self.powerSpecPlot.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.powerSpecPlot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.powerSpecPlot.setObjectName("powerSpecPlot")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 60, 201, 111))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 181, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.STDLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.STDLabel.setObjectName("STDLabel")
        self.verticalLayout_3.addWidget(self.STDLabel)
        self.SampleRateLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.SampleRateLabel.setObjectName("SampleRateLabel")
        self.verticalLayout_3.addWidget(self.SampleRateLabel)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.gridLayout_4.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox1, 2, 0, 1, 4)
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        self.groupBox2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox2.setObjectName("groupBox2")
        self.filelabel = QtWidgets.QLabel(self.groupBox2)
        self.filelabel.setGeometry(QtCore.QRect(10, 146, 500, 10))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filelabel.sizePolicy().hasHeightForWidth())
        self.filelabel.setSizePolicy(sizePolicy)
        self.filelabel.setMinimumSize(QtCore.QSize(500, 0))
        self.filelabel.setMaximumSize(QtCore.QSize(500, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.filelabel.setFont(font)
        self.filelabel.setText("")
        self.filelabel.setObjectName("filelabel")
        self.meandtlabel = QtWidgets.QLabel(self.groupBox2)
        self.meandtlabel.setGeometry(QtCore.QRect(10, 114, 500, 10))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meandtlabel.sizePolicy().hasHeightForWidth())
        self.meandtlabel.setSizePolicy(sizePolicy)
        self.meandtlabel.setMinimumSize(QtCore.QSize(500, 0))
        self.meandtlabel.setMaximumSize(QtCore.QSize(500, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.meandtlabel.setFont(font)
        self.meandtlabel.setText("")
        self.meandtlabel.setObjectName("meandtlabel")
        self.meandwelllabel = QtWidgets.QLabel(self.groupBox2)
        self.meandwelllabel.setGeometry(QtCore.QRect(10, 98, 500, 10))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meandwelllabel.sizePolicy().hasHeightForWidth())
        self.meandwelllabel.setSizePolicy(sizePolicy)
        self.meandwelllabel.setMinimumSize(QtCore.QSize(500, 0))
        self.meandwelllabel.setMaximumSize(QtCore.QSize(500, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.meandwelllabel.setFont(font)
        self.meandwelllabel.setText("")
        self.meandwelllabel.setObjectName("meandwelllabel")
        self.meandelilabel = QtWidgets.QLabel(self.groupBox2)
        self.meandelilabel.setGeometry(QtCore.QRect(10, 82, 500, 10))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meandelilabel.sizePolicy().hasHeightForWidth())
        self.meandelilabel.setSizePolicy(sizePolicy)
        self.meandelilabel.setMinimumSize(QtCore.QSize(500, 0))
        self.meandelilabel.setMaximumSize(QtCore.QSize(500, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.meandelilabel.setFont(font)
        self.meandelilabel.setText("")
        self.meandelilabel.setObjectName("meandelilabel")
        self.eventcounterlabel = QtWidgets.QLabel(self.groupBox2)
        self.eventcounterlabel.setGeometry(QtCore.QRect(10, 130, 500, 10))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventcounterlabel.sizePolicy().hasHeightForWidth())
        self.eventcounterlabel.setSizePolicy(sizePolicy)
        self.eventcounterlabel.setMinimumSize(QtCore.QSize(500, 0))
        self.eventcounterlabel.setMaximumSize(QtCore.QSize(500, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.eventcounterlabel.setFont(font)
        self.eventcounterlabel.setText("")
        self.eventcounterlabel.setObjectName("eventcounterlabel")
        self.verticalGroupBox_5 = QtWidgets.QGroupBox(self.groupBox2)
        self.verticalGroupBox_5.setGeometry(QtCore.QRect(10, 0, 201, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox_5.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_5.setSizePolicy(sizePolicy)
        self.verticalGroupBox_5.setObjectName("verticalGroupBox_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.verticalGroupBox_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 20, 199, 47))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(5, 0, 5, 5)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.eventnumberentry = QtWidgets.QLineEdit(self.layoutWidget1)
        self.eventnumberentry.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventnumberentry.sizePolicy().hasHeightForWidth())
        self.eventnumberentry.setSizePolicy(sizePolicy)
        self.eventnumberentry.setMaximumSize(QtCore.QSize(75, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.eventnumberentry.setFont(font)
        self.eventnumberentry.setObjectName("eventnumberentry")
        self.gridLayout.addWidget(self.eventnumberentry, 0, 2, 1, 1)
        self.previousbutton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousbutton.sizePolicy().hasHeightForWidth())
        self.previousbutton.setSizePolicy(sizePolicy)
        self.previousbutton.setMinimumSize(QtCore.QSize(0, 5))
        self.previousbutton.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.previousbutton.setFont(font)
        self.previousbutton.setObjectName("previousbutton")
        self.gridLayout.addWidget(self.previousbutton, 1, 0, 1, 1)
        self.gobutton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gobutton.sizePolicy().hasHeightForWidth())
        self.gobutton.setSizePolicy(sizePolicy)
        self.gobutton.setMinimumSize(QtCore.QSize(0, 5))
        self.gobutton.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.gobutton.setFont(font)
        self.gobutton.setObjectName("gobutton")
        self.gridLayout.addWidget(self.gobutton, 1, 1, 1, 1)
        self.nextbutton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextbutton.sizePolicy().hasHeightForWidth())
        self.nextbutton.setSizePolicy(sizePolicy)
        self.nextbutton.setMinimumSize(QtCore.QSize(0, 5))
        self.nextbutton.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.nextbutton.setFont(font)
        self.nextbutton.setObjectName("nextbutton")
        self.gridLayout.addWidget(self.nextbutton, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 2)
        self.AxopatchGroup = QtWidgets.QGroupBox(self.groupBox2)
        self.AxopatchGroup.setEnabled(True)
        self.AxopatchGroup.setGeometry(QtCore.QRect(220, 0, 101, 61))
        self.AxopatchGroup.setObjectName("AxopatchGroup")
        self.gridLayoutWidget = QtWidgets.QWidget(self.AxopatchGroup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 19, 101, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ndChannel = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ndChannel.setObjectName("ndChannel")
        self.gridLayout_5.addWidget(self.ndChannel, 0, 0, 1, 1)
        self.makeIVButton = QtWidgets.QPushButton(self.groupBox2)
        self.makeIVButton.setGeometry(QtCore.QRect(390, 80, 113, 32))
        self.makeIVButton.setObjectName("makeIVButton")
        self.verticalGroupBox_6 = QtWidgets.QGroupBox(self.groupBox2)
        self.verticalGroupBox_6.setGeometry(QtCore.QRect(510, 0, 171, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox_6.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_6.setSizePolicy(sizePolicy)
        self.verticalGroupBox_6.setObjectName("verticalGroupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalGroupBox_6)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.showcatbutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showcatbutton.sizePolicy().hasHeightForWidth())
        self.showcatbutton.setSizePolicy(sizePolicy)
        self.showcatbutton.setMinimumSize(QtCore.QSize(0, 0))
        self.showcatbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.showcatbutton.setFont(font)
        self.showcatbutton.setObjectName("showcatbutton")
        self.verticalLayout.addWidget(self.showcatbutton)
        self.concatenatebutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.concatenatebutton.sizePolicy().hasHeightForWidth())
        self.concatenatebutton.setSizePolicy(sizePolicy)
        self.concatenatebutton.setMinimumSize(QtCore.QSize(0, 0))
        self.concatenatebutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.concatenatebutton.setFont(font)
        self.concatenatebutton.setObjectName("concatenatebutton")
        self.verticalLayout.addWidget(self.concatenatebutton)
        self.savecatbutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savecatbutton.sizePolicy().hasHeightForWidth())
        self.savecatbutton.setSizePolicy(sizePolicy)
        self.savecatbutton.setMinimumSize(QtCore.QSize(0, 0))
        self.savecatbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.savecatbutton.setFont(font)
        self.savecatbutton.setObjectName("savecatbutton")
        self.verticalLayout.addWidget(self.savecatbutton)
        self.savefitsbutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savefitsbutton.sizePolicy().hasHeightForWidth())
        self.savefitsbutton.setSizePolicy(sizePolicy)
        self.savefitsbutton.setMinimumSize(QtCore.QSize(0, 0))
        self.savefitsbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.savefitsbutton.setFont(font)
        self.savefitsbutton.setObjectName("savefitsbutton")
        self.verticalLayout.addWidget(self.savefitsbutton)
        self.savetargetbutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savetargetbutton.sizePolicy().hasHeightForWidth())
        self.savetargetbutton.setSizePolicy(sizePolicy)
        self.savetargetbutton.setMinimumSize(QtCore.QSize(0, 0))
        self.savetargetbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.savetargetbutton.setFont(font)
        self.savetargetbutton.setObjectName("savetargetbutton")
        self.verticalLayout.addWidget(self.savetargetbutton)
        self.deleteeventbutton = QtWidgets.QPushButton(self.verticalGroupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteeventbutton.sizePolicy().hasHeightForWidth())
        self.deleteeventbutton.setSizePolicy(sizePolicy)
        self.deleteeventbutton.setMinimumSize(QtCore.QSize(0, 0))
        self.deleteeventbutton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.deleteeventbutton.setFont(font)
        self.deleteeventbutton.setObjectName("deleteeventbutton")
        self.verticalLayout.addWidget(self.deleteeventbutton)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox2)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 0, 171, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 177, 56))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.IVxaxis = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.IVxaxis.setObjectName("IVxaxis")
        self.IVxaxis.addItem("")
        self.IVxaxis.addItem("")
        self.gridLayout_13.addWidget(self.IVxaxis, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_13.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_13.addWidget(self.label_13, 1, 0, 1, 1)
        self.IVyaxis = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.IVyaxis.setObjectName("IVyaxis")
        self.IVyaxis.addItem("")
        self.IVyaxis.addItem("")
        self.gridLayout_13.addWidget(self.IVyaxis, 1, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox2, 1, 1, 1, 3)
        PythIon.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PythIon)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFigure_Saving = QtWidgets.QMenu(self.menubar)
        self.menuFigure_Saving.setObjectName("menuFigure_Saving")
        PythIon.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PythIon)
        self.statusbar.setObjectName("statusbar")
        PythIon.setStatusBar(self.statusbar)
        self.actionInvert = QtWidgets.QAction(PythIon)
        self.actionInvert.setObjectName("actionInvert")
        self.actionsetbuffer = QtWidgets.QAction(PythIon)
        self.actionsetbuffer.setObjectName("actionsetbuffer")
        self.Poresizeraction = QtWidgets.QAction(PythIon)
        self.Poresizeraction.setObjectName("Poresizeraction")
        self.actionBatch_Process = QtWidgets.QAction(PythIon)
        self.actionBatch_Process.setObjectName("actionBatch_Process")
        self.actionSave_All = QtWidgets.QAction(PythIon)
        self.actionSave_All.setObjectName("actionSave_All")
        self.menuFile.addAction(self.Poresizeraction)
        self.menuFile.addAction(self.actionBatch_Process)
        self.menuFigure_Saving.addAction(self.actionSave_All)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFigure_Saving.menuAction())

        self.retranslateUi(PythIon)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(PythIon)

    def retranslateUi(self, PythIon):
        _translate = QtCore.QCoreApplication.translate
        PythIon.setWindowTitle(_translate("PythIon", "PythIon"))
        self.baselinebutton.setText(_translate("PythIon", "BASELINE"))
        self.loadbutton.setText(_translate("PythIon", "LOAD"))
        self.analyzebutton.setText(_translate("PythIon", "ANALYZE"))
        self.previousfilebutton.setText(_translate("PythIon", "PREVIOUS"))
        self.nextfilebutton.setText(_translate("PythIon", "NEXT"))
        self.clearscatterbutton.setText(_translate("PythIon", "CLEAR DATA"))
        self.invertbutton.setText(_translate("PythIon", "INVERT"))
        self.cutbutton.setText(_translate("PythIon", "CUT"))
        self.loaddatabutton.setText(_translate("PythIon", "LOAD DATA"))
        self.fitbutton.setText(_translate("PythIon", "FIT"))
        self.thresholdentry.setText(_translate("PythIon", ".3"))
        self.label_5.setText(_translate("PythIon", "Event Buffer (samples)"))
        self.eventbufferentry.setText(_translate("PythIon", "1000"))
        self.outputsamplerateentry.setText(_translate("PythIon", "4166.67"))
        self.label.setText(_translate("PythIon", "Low Pass Filter (kHz)"))
        self.label_2.setText(_translate("PythIon", "Output Samplerate (kHz)"))
        self.LPentry.setText(_translate("PythIon", "100"))
        self.label_6.setText(_translate("PythIon", "Level Threshold (nA)"))
        self.levelthresholdentry.setText(_translate("PythIon", "None"))
        self.label_3.setText(_translate("PythIon", "Threshold (nA)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("PythIon", "Voltage Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scattertab), _translate("PythIon", "Scatter"))
        self.label_7.setText(_translate("PythIon", "Bins:"))
        self.fracbins.setText(_translate("PythIon", "50"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.frachisttab), _translate("PythIon", "Frac"))
        self.label_9.setText(_translate("PythIon", "Bins"))
        self.delibins.setText(_translate("PythIon", "50"))
        self.label_10.setText(_translate("PythIon", "("))
        self.delirange0.setText(_translate("PythIon", "0"))
        self.label_12.setText(_translate("PythIon", "-"))
        self.delirange1.setText(_translate("PythIon", "1"))
        self.label_11.setText(_translate("PythIon", ")"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.delitab), _translate("PythIon", "Deli"))
        self.label_21.setText(_translate("PythIon", "Bins"))
        self.dwellbins.setText(_translate("PythIon", "100"))
        self.label_22.setText(_translate("PythIon", "("))
        self.dwellrange0.setText(_translate("PythIon", "0"))
        self.label_23.setText(_translate("PythIon", "-"))
        self.dwellrange1.setText(_translate("PythIon", "5"))
        self.label_24.setText(_translate("PythIon", ")"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dwelltab), _translate("PythIon", "Dwell"))
        self.label_25.setText(_translate("PythIon", "Bins"))
        self.dtbins.setText(_translate("PythIon", "100"))
        self.label_26.setText(_translate("PythIon", "("))
        self.dtrange0.setText(_translate("PythIon", "0"))
        self.label_27.setText(_translate("PythIon", "-"))
        self.dtrange1.setText(_translate("PythIon", "1"))
        self.label_28.setText(_translate("PythIon", ")"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dttab), _translate("PythIon", "dt"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("PythIon", "Stats"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("PythIon", "IV Creation"))
        self.poresizeOutput.setText(_translate("PythIon", "TextLabel"))
        self.groupBox_3.setTitle(_translate("PythIon", "Values From IV"))
        self.resistanceText.setText(_translate("PythIon", "TextLabel"))
        self.conductanceText.setText(_translate("PythIon", "TextLabel"))
        self.groupBox_4.setTitle(_translate("PythIon", "Settings"))
        self.resistanceText_2.setText(_translate("PythIon", "Salt Concentration"))
        self.resistanceText_3.setText(_translate("PythIon", "Pore Length"))
        self.groupBox_5.setTitle(_translate("PythIon", "Manual Calculation"))
        self.CustomConductanceLabel_2.setText(_translate("PythIon", "Enter Voltage: "))
        self.CustomConductanceLabel_3.setText(_translate("PythIon", "Enter Current:"))
        self.CustomConductanceLabel.setText(_translate("PythIon", "Enter Conductance:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("PythIon", "Pore Size"))
        self.groupBox_6.setTitle(_translate("PythIon", "Noise Values"))
        self.STDLabel.setText(_translate("PythIon", "TextLabel"))
        self.SampleRateLabel.setText(_translate("PythIon", "TextLabel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("PythIon", "Power Spectrum"))
        self.verticalGroupBox_5.setTitle(_translate("PythIon", "Event Navigation"))
        self.eventnumberentry.setText(_translate("PythIon", "0"))
        self.previousbutton.setText(_translate("PythIon", "Previous"))
        self.gobutton.setText(_translate("PythIon", "Go"))
        self.nextbutton.setText(_translate("PythIon", "Next"))
        self.label_4.setText(_translate("PythIon", "Enter Event Number To View"))
        self.AxopatchGroup.setTitle(_translate("PythIon", "Axopatch Data"))
        self.ndChannel.setText(_translate("PythIon", "Channel 2"))
        self.makeIVButton.setText(_translate("PythIon", "MakeIV"))
        self.showcatbutton.setText(_translate("PythIon", "SHOW CAT. TRACE"))
        self.concatenatebutton.setText(_translate("PythIon", "CONCATENATE"))
        self.savecatbutton.setText(_translate("PythIon", "SAVE CAT. TRACE"))
        self.savefitsbutton.setText(_translate("PythIon", "SAVE EVENT FITS"))
        self.savetargetbutton.setText(_translate("PythIon", "SAVE TARGET"))
        self.deleteeventbutton.setText(_translate("PythIon", "DELETE EVENT"))
        self.groupBox_2.setTitle(_translate("PythIon", "IV Settings"))
        self.IVxaxis.setItemText(0, _translate("PythIon", "Channel 1"))
        self.IVxaxis.setItemText(1, _translate("PythIon", "Channel 2"))
        self.label_8.setText(_translate("PythIon", "IV X-Axis"))
        self.label_13.setText(_translate("PythIon", "IV Y-Axis"))
        self.IVyaxis.setCurrentText(_translate("PythIon", "Channel 1"))
        self.IVyaxis.setItemText(0, _translate("PythIon", "Channel 1"))
        self.IVyaxis.setItemText(1, _translate("PythIon", "Channel 2"))
        self.menuFile.setTitle(_translate("PythIon", "File"))
        self.menuEdit.setTitle(_translate("PythIon", "Edit"))
        self.menuFigure_Saving.setTitle(_translate("PythIon", "Figure Saving"))
        self.actionInvert.setText(_translate("PythIon", "Invert data"))
        self.actionsetbuffer.setText(_translate("PythIon", "Set Event Buffer Size"))
        self.Poresizeraction.setText(_translate("PythIon", "PoreSizer"))
        self.actionBatch_Process.setText(_translate("PythIon", "Batch Process"))
        self.actionSave_All.setText(_translate("PythIon", "Save All"))

from pyqtgraph import GraphicsLayoutWidget, PlotWidget, SpinBox
